
Create docker image using dockerfile;

	1. creae text file cmd;
		
		vim dockerfile
		
		
yum file code:		
		
FROM centos:latest

RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum -y update

RUN yum install -y httpd

COPY index.html /var/www/html/index.html

EXPOSE 80

CMD apachectl -D FOREGROUND
		
		
		
		
		
		
		docker build . -> dot means your current working directory 
		
		if your file save in another directory using this cmd:
		
		docker build -f (your directory path)
		
		ex: docker build -f /var/tmp/dockerfile
		
		docker build -t (image name:tag) .
		